function map_integrate_dialogue(data)
fh=figure('Name', ' Range for E Integrating Map',...
        'units','normalized', ...
        'Position',[0.3,0.3,0.18,0.1],...
        'Color',[0.6 0.6 0.6],...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Resize','off');

    
str1 = num2str(data.e'*1000);
lower_range = uicontrol(fh,'Style', 'popup',... 
       'units','normalized',...
       'Value',1,...
       'String', str1,...
       'Position', [0.02 0.2 0.3 0.5]);
uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Lower Bound',...
    'Position',[0.02 0.75 0.3 0.15]);
  
str2 = str1 ;
upper_range = uicontrol(fh,'Style', 'popup',... 
       'units','normalized',...
       'Value',1,...
       'String', str2,...
       'Position', [0.35 0.2 0.3 0.5]);
uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Upper Bound',...
    'Position',[0.35 0.75 0.3 0.15]);   
   
OK_but = uicontrol(fh,'Style','pushbutton',...
       'String','OK',...
       'units','normalized',...
       'Position',[0.7 0.55 0.25 0.25],...
       'Callback',@OK_Callback);

 cancel_but = uicontrol(fh,'Style','pushbutton',...
       'String','Cancel',...
       'units','normalized',...
       'Position',[0.7 0.25 0.25 0.25],...
       'Callback',@cancel_Callback);
    
    function OK_Callback(hObject,eventdata)
        lower_bnd_ind = (get(lower_range,'Value'));
        upper_bnd_ind = (get(upper_range,'Value'));
        bnd1 = min(lower_bnd_ind,upper_bnd_ind);
        bnd2 = max(lower_bnd_ind,upper_bnd_ind);
        old_data = data;
        map = old_data.map;
        delta_e = 1000*abs(old_data.e(1) - old_data.e(2));
        int_map = sum(map(:,:,bnd1:bnd2),3);        
        new_data = old_data;
        new_data.map = int_map;
        new_data.ave = [];
        new_data.e = 1;
        new_data.ops{end+1} = ['integrate map from layer ' num2str(bnd1) ' to layer ' num2str(bnd2)];
        new_data.var = ['int_map(' num2str(bnd1) '->' num2str(bnd2) ')'];
        img_obj_viewer2(new_data);        
    end
    function cancel_Callback(hObject,eventdata)
        close(fh);
    end
end