function general_linear2D_image_correct_dialogue(data)

h1 = figure(...
'Units','characters',...
'Color',[0.7 0.7 0.7],...
'MenuBar','none',...
'Name','Linear 2D Image Correct',...
'NumberTitle','off',...
'Position',[50 10 70 35],...
'Resize','off',...
'Visible','on');

img1_title = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Position',[5 32.5 25 1.2],...
'String',{'Geometry'},...
'Style','text',...
'FontWeight','Bold');

img1_axes = axes(...
'Parent',h1,...
'Units','characters',...
'Position',[5 20 25 12]);

polygon_choice = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Position',[5 16 14 1.5],...
'String',{ '4';'6';'8' },...
'Style','popupmenu',...
'Value',1,...
'Callback',@plot_img1_Callback);

end