function peak_fit2D_dialogue(img)
[nr nc] = size(img);
%enter the Q vectors position and width on which to measurement different 
%form factors
fh=figure('Name', '2D Peak Fit',...
    'units','pixels', ...
    'Position',[500,500,370,300],...
    'Color',[0.6 0.6 0.6],...
    'MenuBar', 'none',...
    'NumberTitle', 'off',...
    'Resize','off');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','INITIAL ESTIMATES',...
    'Fontweight','bold',...
    'Position', [10 278 290 20]);

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','x0 (pxl)',...
     'Fontweight','bold',...
    'Position', [10 250 70 20]);
x0_input = uicontrol(fh,'Style', 'edit',...
    'units','pixels',...
    'Position', [10 228 70 20],...
    'String','0');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','y0 (pxl)',...
     'Fontweight','bold',...
    'Position', [10 200 70 20]);
y0_input = uicontrol(fh,'Style','edit',...
    'units','pixels',...
    'Position',[10 178 70 20],...
    'String','0');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','Ampltidue',...
     'Fontweight','bold',...
    'Position', [10 150 70 20]);
amp_input = uicontrol(fh,'Style','edit',...
    'units','pixels',...
    'Position',[10 128 70 20],...
    'String','0');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','std_x (pxl)',...
     'Fontweight','bold',...
    'Position', [120 250 70 20]);
std_x_input = uicontrol(fh,'Style', 'edit',...
    'units','pixels',...
    'Position', [120 228 70 20],...
    'String','0');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','std_y (pxl)',...
     'Fontweight','bold',...
    'Position', [120 200 70 20]);
std_y_input = uicontrol(fh,'Style', 'edit',...
    'units','pixels',...
    'Position', [120 178 70 20],...
    'String','0');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','Angle',...
     'Fontweight','bold',...
    'Position', [120 150 70 20]);
angle_input = uicontrol(fh,'Style','edit',...
    'units','pixels',...
    'Position',[120 128 70 20],...
    'String','0');
  
uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','const',...
     'Fontweight','bold',...
    'Position', [230 250 70 20]);
const_input = uicontrol(fh,'Style','edit',...
    'units','pixels',...
    'Position',[230 228 70 20],...
    'String','0');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','lin X',...
     'Fontweight','bold',...
    'Position', [230 200 70 20]);
linX_input = uicontrol(fh,'Style','edit',...
    'units','pixels',...
    'Position',[230 178 70 20],...
    'String','0');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','lin Y',...
     'Fontweight','bold',...
    'Position', [230 150 70 20]);
linY_input = uicontrol(fh,'Style','edit',...
    'units','pixels',...
    'Position',[230 128 70 20],...
    'String','0');

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','Window 1/2 width at (x0,y0) (pxl)',...
     'Fontweight','bold',...
    'Position', [50 70 120 35]);
window_input = uicontrol(fh,'Style', 'edit',...
    'units','pixels',...
    'Position', [75 48 70 20],...
    'String',num2str(floor(nr/2)));

uicontrol(fh,'Style','text',...
    'units','pixels',...
    'String','Peak Type',...
     'Fontweight','bold',...
    'Position',[200 80 80 20]);
pk_type_drop = uicontrol(fh,'Style','popup',...
    'units','pixels',...
    'Position',[200 48 85 30],...
    'String','Gaussian|Lorentzian',...
    'Value',1);

OK_but = uicontrol(fh,'Style','pushbutton',...
       'String','OK',...
       'units','pixels',...
       'Position',[110 10 60 20],...
       'Callback',@OK_Callback);

 done_but = uicontrol(fh,'Style','pushbutton',...
       'String','Done',...
       'units','pixels',...
       'Position',[190 10 60 20],...
       'Callback',@done_Callback);

   
%%%%%%%%%%%%%%%%%%%%%%%%CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function OK_Callback(hObject,eventdata)
    x0 = str2num(get(x0_input,'String'));
    y0 = str2num(get(y0_input,'String'));    
    A = str2num(get(amp_input,'String'));
    std_x = str2num(get(std_x_input,'String'));
    std_y = str2num(get(std_y_input,'String'));
    angle = str2num(get(angle_input,'String'));    
    window_w = str2num(get(window_input,'String')); 
    const = str2num(get(const_input,'String'));
    lin_x = str2num(get(linX_input,'String'));
    lin_y = str2num(get(linY_input,'String'));
    peak_type = get(pk_type_drop,'Value');
    peak_fit2D(x0,y0,A,std_x,std_y,angle,const,lin_x,lin_y,window_w,img,peak_type)
end

function done_Callback(hObject,eventdata)       
        close(fh);
end
end