function QPI_r_amplitude_dialogue(data)
color_map_path = 'C:\Analysis Code\MATLAB\STM View\Color Maps\';             
cols = struct2cell(load([color_map_path 'RedWhiteBlue.mat']));
cols = cols{1};
%enter the Q vectors position and width on which to measurement different 
%form factors
fh=figure('Name', 'QPI Q vectors + Filter Width',...
        'units','normalized', ...
        'Position',[0.3,0.3,0.3,0.1],...
        'Color',[0.6 0.6 0.6],...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Resize','off');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q1x',...
       'Position', [0.05 0.85 0.12 0.15]);
Q1x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.05 0.58 0.12 0.25],...
        'String','50');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q1y',...
       'Position', [0.05 0.35 0.12 0.15]);
Q1y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.05 0.08 0.12 0.25],...
        'String','50');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q2x',...
    'Position', [0.25 0.85 0.12 0.15]);  
Q2x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.25 0.58 0.12 0.25],...
       'String','-50');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q2y',...
       'Position', [0.25 0.35 0.12 0.15]);  
Q2y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.25 0.08 0.12 0.25],...
        'String','50');
   
uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Filter Width',...
    'Position', [0.45 0.55 0.12 0.15]);
filt_width = uicontrol(fh,'Style','edit',...
    'units','normalized',...
    'Position',[0.45 0.25 0.12 0.25],...
    'String','50');
    
OK_but = uicontrol(fh,'Style','pushbutton',...
       'String','OK',...
       'units','normalized',...
       'Position',[0.7 0.6 0.25 0.25],...
       'Callback',@OK_Callback);

 cancel_but = uicontrol(fh,'Style','pushbutton',...
       'String','Cancel',...
       'units','normalized',...
       'Position',[0.7 0.25 0.25 0.25],...
       'Callback',@cancel_Callback);

%%%%%%%%%%%%%%%%%%%%%%%%CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function OK_Callback(hObject,eventdata)
    q_px(1,1) = str2num(get(Q1x,'String'));
    q_px(2,1) = str2num(get(Q1y,'String'));
    q_px(1,2) = str2num(get(Q2x,'String'));
    q_px(2,2) = str2num(get(Q2y,'String'));
    filt_w = str2num(get(filt_width,'String'));  
    QPI_r_amplitude(q_px,filt_w,data);
end

function cancel_Callback(hObject,eventdata)       
        close(fh);
end
end
